name: Publish docs via GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      # Rebuild website when docs have changed or code has changed
      - "README.md"
      - "docs/**"
      - "mkdocs.yml"
      - "**.py"
  workflow_dispatch:

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install \
            stac_fastapi/api[docs] \
            stac_fastapi/types[docs] \
            stac_fastapi/extensions[docs] \

      - name: update API docs
        run: |
          pdocs as_markdown \
            --output_dir docs/api/ \
            --exclude_source \
            --overwrite \
            stac_fastapi
        env:
          POSTGRES_USER: username
          POSTGRES_PASS: password
          POSTGRES_DBNAME: postgis
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_HOST_READER: localhost
          POSTGRES_HOST_WRITER: localhost

      - name: Deploy docs
        run: mkdocs gh-deploy --force
